name: NuGet

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
          
      - name: Pack BrokerR.Http
        run: dotnet pack BrokerR.Http --configuration Release --include-symbols --include-source
        
      - name: Publish BrokerR.Http
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUPKG_PROJECT: BrokerR.Http
        run: ./nuget
        
      - name: Pack BrokerR.Http.Client
        run: dotnet pack BrokerR.Http.Client --configuration Release --include-symbols --include-source
        
      - name: Publish BrokerR.Http.Client
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUPKG_PROJECT: BrokerR.Http.Client
        run: ./nuget
